package com.lovoteweb.mallproject.mbg.mapper;

import com.lovoteweb.mallproject.mbg.model.ProCommentReply;
import com.lovoteweb.mallproject.mbg.model.ProCommentReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProCommentReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int countByExample(ProCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByExample(ProCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insert(ProCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insertSelective(ProCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    List<ProCommentReply> selectByExample(ProCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    ProCommentReply selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProCommentReply record, @Param("example") ProCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExample(@Param("record") ProCommentReply record, @Param("example") ProCommentReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKeySelective(ProCommentReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKey(ProCommentReply record);
}