package com.lovoteweb.mallproject.mbg.mapper;

import com.lovoteweb.mallproject.mbg.model.ProProduct;
import com.lovoteweb.mallproject.mbg.model.ProProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int countByExample(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByExample(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insert(ProProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insertSelective(ProProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    List<ProProduct> selectByExampleWithBLOBs(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    List<ProProduct> selectByExample(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    ProProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProProduct record, @Param("example") ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ProProduct record, @Param("example") ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExample(@Param("record") ProProduct record, @Param("example") ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKeySelective(ProProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ProProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKey(ProProduct record);
}