package com.lovoteweb.mallproject.mbg.mapper;

import com.lovoteweb.mallproject.mbg.model.ProProductCategory;
import com.lovoteweb.mallproject.mbg.model.ProProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int countByExample(ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByExample(ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insert(ProProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insertSelective(ProProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    List<ProProductCategory> selectByExampleWithBLOBs(ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    List<ProProductCategory> selectByExample(ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    ProProductCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProProductCategory record, @Param("example") ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ProProductCategory record, @Param("example") ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExample(@Param("record") ProProductCategory record, @Param("example") ProProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKeySelective(ProProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ProProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product_category
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKey(ProProductCategory record);
}