package com.lovoteweb.mallproject.mbg.mapper;

import com.lovoteweb.mallproject.mbg.model.UmsUserpermissionrelation;
import com.lovoteweb.mallproject.mbg.model.UmsUserpermissionrelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UmsUserpermissionrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int countByExample(UmsUserpermissionrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByExample(UmsUserpermissionrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insert(UmsUserpermissionrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int insertSelective(UmsUserpermissionrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    List<UmsUserpermissionrelation> selectByExample(UmsUserpermissionrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    UmsUserpermissionrelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") UmsUserpermissionrelation record, @Param("example") UmsUserpermissionrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByExample(@Param("record") UmsUserpermissionrelation record, @Param("example") UmsUserpermissionrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKeySelective(UmsUserpermissionrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    int updateByPrimaryKey(UmsUserpermissionrelation record);
}