package com.lovoteweb.mallproject.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OmsCartItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.member_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.quantity
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.product_price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.create_time
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_cart_item.delete_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer deleteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_cart_item
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.id
     *
     * @return the value of oms_cart_item.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.id
     *
     * @param id the value for oms_cart_item.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_id
     *
     * @return the value of oms_cart_item.product_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_id
     *
     * @param productId the value for oms_cart_item.product_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.member_id
     *
     * @return the value of oms_cart_item.member_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.member_id
     *
     * @param memberId the value for oms_cart_item.member_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.quantity
     *
     * @return the value of oms_cart_item.quantity
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.quantity
     *
     * @param quantity the value for oms_cart_item.quantity
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.price
     *
     * @return the value of oms_cart_item.price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.price
     *
     * @param price the value for oms_cart_item.price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_name
     *
     * @return the value of oms_cart_item.product_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_name
     *
     * @param productName the value for oms_cart_item.product_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.product_price
     *
     * @return the value of oms_cart_item.product_price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.product_price
     *
     * @param productPrice the value for oms_cart_item.product_price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.create_time
     *
     * @return the value of oms_cart_item.create_time
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.create_time
     *
     * @param createTime the value for oms_cart_item.create_time
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_cart_item.delete_status
     *
     * @return the value of oms_cart_item.delete_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_cart_item.delete_status
     *
     * @param deleteStatus the value for oms_cart_item.delete_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_cart_item
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", memberId=").append(memberId);
        sb.append(", quantity=").append(quantity);
        sb.append(", price=").append(price);
        sb.append(", productName=").append(productName);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}