package com.lovoteweb.mallproject.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class OmsOrderItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.order_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_quantity
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer productQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order_item
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.id
     *
     * @return the value of oms_order_item.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.id
     *
     * @param id the value for oms_order_item.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.order_id
     *
     * @return the value of oms_order_item.order_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.order_id
     *
     * @param orderId the value for oms_order_item.order_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_id
     *
     * @return the value of oms_order_item.product_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_id
     *
     * @param productId the value for oms_order_item.product_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_name
     *
     * @return the value of oms_order_item.product_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_name
     *
     * @param productName the value for oms_order_item.product_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_price
     *
     * @return the value of oms_order_item.product_price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_price
     *
     * @param productPrice the value for oms_order_item.product_price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_quantity
     *
     * @return the value of oms_order_item.product_quantity
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_quantity
     *
     * @param productQuantity the value for oms_order_item.product_quantity
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productQuantity=").append(productQuantity);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}