package com.lovoteweb.mallproject.mbg.model;

import java.io.Serializable;

public class ProBrand implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.factory_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer factoryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.show_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer showStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.product_count
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.logo
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_brand.brand_story
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String brandStory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pro_brand
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.id
     *
     * @return the value of pro_brand.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.id
     *
     * @param id the value for pro_brand.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.name
     *
     * @return the value of pro_brand.name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.name
     *
     * @param name the value for pro_brand.name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.factory_status
     *
     * @return the value of pro_brand.factory_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getFactoryStatus() {
        return factoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.factory_status
     *
     * @param factoryStatus the value for pro_brand.factory_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setFactoryStatus(Integer factoryStatus) {
        this.factoryStatus = factoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.show_status
     *
     * @return the value of pro_brand.show_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.show_status
     *
     * @param showStatus the value for pro_brand.show_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.product_count
     *
     * @return the value of pro_brand.product_count
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.product_count
     *
     * @param productCount the value for pro_brand.product_count
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.logo
     *
     * @return the value of pro_brand.logo
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.logo
     *
     * @param logo the value for pro_brand.logo
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_brand.brand_story
     *
     * @return the value of pro_brand.brand_story
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getBrandStory() {
        return brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_brand.brand_story
     *
     * @param brandStory the value for pro_brand.brand_story
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setBrandStory(String brandStory) {
        this.brandStory = brandStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_brand
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", factoryStatus=").append(factoryStatus);
        sb.append(", showStatus=").append(showStatus);
        sb.append(", productCount=").append(productCount);
        sb.append(", logo=").append(logo);
        sb.append(", brandStory=").append(brandStory);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}