package com.lovoteweb.mallproject.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class ProCommentReply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.comment_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.member_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.member_icon
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String memberIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.content
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.create_time
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_comment_reply.type
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.id
     *
     * @return the value of pro_comment_reply.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.id
     *
     * @param id the value for pro_comment_reply.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.comment_id
     *
     * @return the value of pro_comment_reply.comment_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.comment_id
     *
     * @param commentId the value for pro_comment_reply.comment_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.member_name
     *
     * @return the value of pro_comment_reply.member_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.member_name
     *
     * @param memberName the value for pro_comment_reply.member_name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.member_icon
     *
     * @return the value of pro_comment_reply.member_icon
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getMemberIcon() {
        return memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.member_icon
     *
     * @param memberIcon the value for pro_comment_reply.member_icon
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setMemberIcon(String memberIcon) {
        this.memberIcon = memberIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.content
     *
     * @return the value of pro_comment_reply.content
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.content
     *
     * @param content the value for pro_comment_reply.content
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.create_time
     *
     * @return the value of pro_comment_reply.create_time
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.create_time
     *
     * @param createTime the value for pro_comment_reply.create_time
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_comment_reply.type
     *
     * @return the value of pro_comment_reply.type
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_comment_reply.type
     *
     * @param type the value for pro_comment_reply.type
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_comment_reply
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", commentId=").append(commentId);
        sb.append(", memberName=").append(memberName);
        sb.append(", memberIcon=").append(memberIcon);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}