package com.lovoteweb.mallproject.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ProProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.picture
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.delete_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.publish_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.new_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer newStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.recommand_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer recommandStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.verify_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer verifyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.sale
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.stock
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.low_stock
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Integer lowStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.unit
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.weight
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.service_ids
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String serviceIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.keywords
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.brand_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.product_category_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long productCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_product.description
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.id
     *
     * @return the value of pro_product.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.id
     *
     * @param id the value for pro_product.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.name
     *
     * @return the value of pro_product.name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.name
     *
     * @param name the value for pro_product.name
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.picture
     *
     * @return the value of pro_product.picture
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.picture
     *
     * @param picture the value for pro_product.picture
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.delete_status
     *
     * @return the value of pro_product.delete_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.delete_status
     *
     * @param deleteStatus the value for pro_product.delete_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.publish_status
     *
     * @return the value of pro_product.publish_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.publish_status
     *
     * @param publishStatus the value for pro_product.publish_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.new_status
     *
     * @return the value of pro_product.new_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getNewStatus() {
        return newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.new_status
     *
     * @param newStatus the value for pro_product.new_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setNewStatus(Integer newStatus) {
        this.newStatus = newStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.recommand_status
     *
     * @return the value of pro_product.recommand_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getRecommandStatus() {
        return recommandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.recommand_status
     *
     * @param recommandStatus the value for pro_product.recommand_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setRecommandStatus(Integer recommandStatus) {
        this.recommandStatus = recommandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.verify_status
     *
     * @return the value of pro_product.verify_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.verify_status
     *
     * @param verifyStatus the value for pro_product.verify_status
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setVerifyStatus(Integer verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.sale
     *
     * @return the value of pro_product.sale
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.sale
     *
     * @param sale the value for pro_product.sale
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.price
     *
     * @return the value of pro_product.price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.price
     *
     * @param price the value for pro_product.price
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.stock
     *
     * @return the value of pro_product.stock
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.stock
     *
     * @param stock the value for pro_product.stock
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.low_stock
     *
     * @return the value of pro_product.low_stock
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Integer getLowStock() {
        return lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.low_stock
     *
     * @param lowStock the value for pro_product.low_stock
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setLowStock(Integer lowStock) {
        this.lowStock = lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.unit
     *
     * @return the value of pro_product.unit
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.unit
     *
     * @param unit the value for pro_product.unit
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.weight
     *
     * @return the value of pro_product.weight
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.weight
     *
     * @param weight the value for pro_product.weight
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.service_ids
     *
     * @return the value of pro_product.service_ids
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getServiceIds() {
        return serviceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.service_ids
     *
     * @param serviceIds the value for pro_product.service_ids
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setServiceIds(String serviceIds) {
        this.serviceIds = serviceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.keywords
     *
     * @return the value of pro_product.keywords
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.keywords
     *
     * @param keywords the value for pro_product.keywords
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.brand_id
     *
     * @return the value of pro_product.brand_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.brand_id
     *
     * @param brandId the value for pro_product.brand_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.product_category_id
     *
     * @return the value of pro_product.product_category_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.product_category_id
     *
     * @param productCategoryId the value for pro_product.product_category_id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setProductCategoryId(Long productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_product.description
     *
     * @return the value of pro_product.description
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_product.description
     *
     * @param description the value for pro_product.description
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_product
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", picture=").append(picture);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", publishStatus=").append(publishStatus);
        sb.append(", newStatus=").append(newStatus);
        sb.append(", recommandStatus=").append(recommandStatus);
        sb.append(", verifyStatus=").append(verifyStatus);
        sb.append(", sale=").append(sale);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append(", lowStock=").append(lowStock);
        sb.append(", unit=").append(unit);
        sb.append(", weight=").append(weight);
        sb.append(", serviceIds=").append(serviceIds);
        sb.append(", keywords=").append(keywords);
        sb.append(", brandId=").append(brandId);
        sb.append(", productCategoryId=").append(productCategoryId);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}