package com.lovoteweb.mallproject.mbg.model;

import java.io.Serializable;

public class UmsUserpermissionrelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_userpermissionRelation.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_userpermissionRelation.pid
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_userpermissionRelation.uid
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_userpermissionRelation.id
     *
     * @return the value of ums_userpermissionRelation.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_userpermissionRelation.id
     *
     * @param id the value for ums_userpermissionRelation.id
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_userpermissionRelation.pid
     *
     * @return the value of ums_userpermissionRelation.pid
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_userpermissionRelation.pid
     *
     * @param pid the value for ums_userpermissionRelation.pid
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_userpermissionRelation.uid
     *
     * @return the value of ums_userpermissionRelation.uid
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_userpermissionRelation.uid
     *
     * @param uid the value for ums_userpermissionRelation.uid
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_userpermissionRelation
     *
     * @mbggenerated Fri Jun 26 16:09:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", uid=").append(uid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}